name: 'Assert Branch Naming Convention'
on:
  push

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[0-9]+$' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature/SOC-,bugfix/SOC-,hotfix/SOC-' # All branches should start with the given prefix
          ignore: master,main,develop # Ignore exactly matching branch names from convention
          min_length: 12 # Min length of the branch name
          max_length: 20 # Max length of the branch name
