name: Scheduled Scratch Org Pool

on:
  schedule:
    - cron: '0 22 * * 0-4' # Sunday - Thursday at 10 PM UTC
    - cron: '0 10 * * 1-5' # Monday - Friday at 10 AM UTC

jobs:
  create-ci-pool:
    name: 'Create CI Pool'
    uses: ./.github/workflows/create-scratch-org-pool.yml
    with:
      pool: ci-pool
    secrets: inherit

  create-dev-pool:
    name: 'Create Dev Pool'
    uses: ./.github/workflows/create-scratch-org-pool.yml
    with:
      pool: dev-pool
    secrets: inherit
