name: Scheduled Scratch Org Pool

on:
  schedule:
    - cron: '0 0 0 ? APR * *' # 10 PM UTC on weekdays

jobs:
  create-ci-pool:
    name: 'Create CI Pool'
    uses: ./.github/workflows/create-scratch-org-pool.yml
    with:
      pool-config: ./config/pools/ci-pool.json
    secrets: inherit

  create-dev-pool:
    name: 'Create Dev Pool'
    uses: ./.github/workflows/create-scratch-org-pool.yml
    with:
      pool-config: ./config/pools/dev-pool.json
    secrets: inherit
